### ISSUE TITLE
Vote Tracking

### ISSUE THREAD

**Issue by ukstv** [my-dao-dashboard/daoscan#1]
- [ ] Track vote created event
- [ ] Track individual votes
- [ ] Report votes in GraphQL
  - when created,
  - by whom,
  - purpose,
  - rejected or accepted,
  - yes/no stats
  - history of actions
